# Generated by Django 4.0.4 on 2022-05-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
