# Generated by Django 4.0.4 on 2022-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl_collection', '0002_alter_vinyl_genre_alter_vinyl_image_alter_vinyl_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='discogs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
