# Generated by Django 4.0.4 on 2022-06-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl_collection', '0005_alter_vinyl_format_alter_vinyl_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
