# Generated by Django 4.0.4 on 2022-06-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl_collection', '0006_alter_user_created_at_alter_vinyl_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinyl',
            options={'ordering': ('-artist', '-album')},
        ),
    ]
